language: go
matrix:
  include:
    - go: 1.8.x
    - go: 1.9.x

install:
  - go get github.com/golang/lint/golint
  - go get ./...
  - go install .

script:
  - go generate ./...
  - esc -o static.go testdata
  - go test -v ./...
  - go vet ./...
  - LINT=$(golint ./...) && echo $LINT
  - test -z "$LINT"
  - GOFMT=$(gofmt -s -d .) && echo $GOFMT
  - test -z "$GOFMT"
